[package]
name = "safenet"
version = "0.1.0"
edition = "2021"

[dependencies]
blake2 = { version = "0.10.6" }
chacha20poly1305 = "0.10.1"
once_cell = "1.17.1"
p384 = "0.12.0"
pbkdf2 = "0.11.0"
rand = "0.8.5"
tinyhttp = { git = "https://github.com/mateocabanal/tinyhttp", default-features = false, features = ["sys"] }
minreq = "2.6.0"
log = "0.4.17"
generic-array = "0.14.7"
uuid = { version = "1.3.0", features = ["v4", "fast-rng"] }
local-ip-address = "0.5.1"

[dev-dependencies]
clap = { version = "4.2.1", features = ["derive"] }
simple_logger = "4.0.0"
dialoguer = "0.10.3"
