[package]
name = "safenet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake2 = { version = "0.10.6" }
chacha20poly1305 = "0.10.1"
once_cell = "1.17.1"
p384 = "0.12.0"
pbkdf2 = "0.11.0"
rand = "0.8.5"
tinyhttp = "0.3.0"
minreq = "2.6.0"
log = "0.4.17"
simple_logger = "4.0.0"

[dev-dependencies]
