name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build - ${{ matrix.platform.release_for }}
    strategy:
      matrix:
        platform:
          - release_for: Linux - x86_64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            command: both

          - release_for: Windows - x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            command: both

          - release_for: MacOS - x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
            command: both
            
    runs-on: ${{ matrix.platform.os }}
    steps:
    - uses: Swatinem/rust-cache@v2
    - uses: actions/checkout@v3
    - name: Unit Tests
      uses: houseabsolute/actions-rust-cross@v0
      with:
          command: ${{ matrix.platform.command }}
          target: ${{ matrix.platform.target }}
